### ISSUE TITLE
How does one configure Sortier

### ISSUE THREAD

**Issue by robjac** [snowcoders/sortier#357]
# Language
JS

The documentation for configuration is really vague; if not non-existent.

I'd like to configure it to run on Scss as the docs mention. 

Super confused here.

What does a cosmic config for sortier look like? Just an example would be helpful. I know you're busy, but hoping to get the attention of others in this issue.

**Comment by k2snowman69** [comment]
No worries, let's see if we can clear this up a bit :-)

**Running sortier on scss files**
You would pass a glob into sortier as a parameter that describes the scss files you wish to run it on. For example, the following will run sortier on all scss files that are in all subdirectories (and I think the current directory). 
```
sortier "./**/*.scss"
```

**Cosmiconfig**
[Cosmiconfig](https://github.com/davidtheclark/cosmiconfig) is an npm package that allows you to use all sorts of files to define your configuration file. I'm partial to using the *.js file type because I like the importing my configuration files from a shared repository but for all options I do suggest you go to their github or npm package.

For the configuration options themselves, if you go to the [docs page](https://snowcoders.github.io/sortier/#/options-general) any of the examples are partial objects that can be merged together. Here's an example merging some general options, the css options and the js options:
```
{
  "logLevel": "diagnostic",
  "css": {
    "sortDeclarations": {
      overrides: ["display", "*"]
    }
  },
  "js": {
    "sortImportDeclarations": "source"
  }
}
``` 

Hopefully that helps, let me know if you have any other questions :-)
